### PR TITLE
pushing to use new vcs and see diff

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@scottwittenburg some of the fail are worth taking a look, plot shifted a bit and "fillarea" test blurs outside of crop zone

**Comment by scottwittenburg** [comment]
Thanks @doutriaux1 I'll take a look.

**Comment by scottwittenburg** [comment]
@doutriaux1 Do you have any idea what happened on the linux py2 tests here?  No tests were run, seemingly due to a `gcc` error compiling `shpopen.c`.  Also, on the osx side, do you know where I can find the uploaded artifacts?  Somehow I'm missing those, so I can't look at the diffs you pointed out.

**Comment by doutriaux1** [comment]
@scottwittenburg it took my all day but yes I know. @danlipsa this is due to VTK. Because we do NOT compile vtk-cdat using the "correct" (these days) compiler(c) we use `toolchain` the issue is that everything else including setuptools uses the correct wa. BUT when you bring in vtk-cdat the activate further reset the CC env variable to `gcc` rather than the super complicated long name and that then crashes because it obviously does not understand the gcc7 flags...

**Comment by doutriaux1** [comment]
short version of this is we need to figure out how to compile vtk-cdat using the "compiler("c") flag. @danlipsa any chance you could tackle this?

**Comment by doutriaux1** [comment]
@danlipsa @scottwittenburg I have a temporary fix for now, using $GCC rather than $CC when presetn, please review and approve

**Pull request merged**
